# Generated by Django 5.0.3 on 2024-03-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variaveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.BooleanField(default=False)),
                ('botao', models.BooleanField(default=False)),
                ('liga_robo', models.BooleanField(default=False)),
                ('reset_contador', models.BooleanField(default=False)),
                ('valor_contagem', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Exemplo',
        ),
    ]
